### ISSUE TITLE
Dependency on pre-release mobject libs

### ISSUE THREAD

**Issue by benhar-dev** [Mobject-Dev-Team/mobject-datatypes#1]
[Prerelease.zip](https://github.com/Mobject-Dev-Team/mobject-types/files/14204211/Prerelease.zip)

Currently the beta relies on features of a prerelease set of libs. 

mobject-serialization v0.2.0 and mobject-json v1.1.0

These can be found in the zip.

**Comment by AndyP01** [comment]
These are required now:

mobject-disposable,1.0.0
mobject-enumerable,1.1.0
mobject-collections,1.1.0
mobject-serialization,0.4.0

**Comment by benhar-dev** [comment]
https://github.com/Mobject-Dev-Team/mobject-disposable
https://github.com/Mobject-Dev-Team/mobject-enumerable/tree/pre-1.1.0
https://github.com/Mobject-Dev-Team/mobject-collections/tree/pre-v1.1.0
https://github.com/Mobject-Dev-Team/mobject-serialization/tree/pre-v0.4.0

**Comment by benhar-dev** [comment]
No longer needed.  All libs are released.
